### ISSUE TITLE
[Maven] Missing dependency

### ISSUE THREAD

**Issue by brunothiao** [stain/owlapi-jsonld#3]
Hi,

There is a missing dependency with Maven. I had to add inside my pom.xml the owlapi-apibinding to use the JSON-LD parser/writer.

``` xml
        <dependency>
            <groupId>net.sourceforge.owlapi</groupId>
            <artifactId>owlapi-apibinding</artifactId>
            <version>3.5.0</version>
        </dependency>
```

Cheers,
Bruno

**Comment by stain** [comment]
Thanks, I guess I assumed you would have owlapi-apibinding anyway.
